@user_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI3NzIzNjV9.ncgc55MZPIshlE-OYrLCgcpDCjPP17xcO6LPaRBf_UU

@restaurant_jwt = eyJhbGciOiJIUzI1NiJ9.eyJyZXN0YXVyYW50X2lkIjozLCJleHAiOjE2NzI4NTkyNzJ9.30xDntm4VQT4EUuAz3Ie3uttUDYGCHrpuYzf3uQAXRU

@user2_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2NzI4NTg4NTZ9.fPx8Jbf7IJAlpdoABzEKtgfL4L3MUn0fDsfm6U3uRJY

@restaurant2_jwt = eyJhbGciOiJIUzI1NiJ9.eyJyZXN0YXVyYW50X2lkIjoyLCJleHAiOjE2NzI3NzM2NTB9.wd7QMFlz9xGedXWXa7ixHlUysTYuMvvIS4IHYjFJUr0

@connor_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2NzI4NTQxODh9.Z0xVFThc1uekZPwWW3REFBZi6qQI-ZnREw1uQtAqEKQ

### USER CREATE
POST http://localhost:3000/users.json
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "name": "Connor",
  "email": "connor@example.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "image.gov"
}






### RESTAURANT CREATE


POST http://localhost:3000/restaurants.json
Content-Type: application/json
# Authorization: Bearer {{jwt}}

{
  "name": "Test Indian",
  "email": "testindian@example.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "image.gov"
}


### SESSIONS CREATE

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "eric@example.com",
  "password": "password"
}

### RESTAURANT SESSIONS CREATE

POST http://localhost:3000/restaurant_sessions.json
Content-Type: application/json

{
  "email": "testpizzeria@example.com",
  "password": "password"
}


### USER DESTROY

DELETE http://localhost:3000/users/2.json
Content-Type: application/json
Authorization: Bearer {{user2_jwt}}

### RESTAURANT DESTROY

DELETE http://localhost:3000/restaurants/2.json
Content-Type: application/json
Authorization: Bearer {{restaurant2_jwt}}

### FAVORITES CREATE

POST http://localhost:3000/favorites.json
Content-Type: application/json
Authorization: Bearer {{user2_jwt}}

{
  "restaurant_id": 4
}

### USERS INDEX

GET http://localhost:3000/users/.json

### TAGS CREATE

POST http://localhost:3000/tags.json
Content-Type: application/json
Authorization: Bearer {{user2_jwt}}

{
  "vegan": true,
  "vegetarian": true,
  "spicy": true,
  "gluten_free": true
}

### DELETE TAGS

DELETE http://localhost:3000/tags/2.json
Content-Type: application/json
Authorization: Bearer {{connor_jwt}}


### RESTAURANT TAGS EDIT

PATCH http://localhost:3000/restaurant_tags/1.json
Content-Type: application/json
Authorization: Bearer {{restaurant_jwt}}

{
  "vegetarian": true
}